### ISSUE TITLE
Installing with NPM gives a different result to installation with Bower

### ISSUE THREAD

**Issue by shanecarmody** [basscss/basscss-sass#13] opened 2016-02-27 21:42 UTC
I don’t know if this is intended but when I install `basscss-sass` to my project using the `npm install basscss-sass` command. I get the following list of folders installed with no sign of any Sass files:

<img width="194" alt="screen shot 2016-02-27 at 22 37 10" src="https://cloud.githubusercontent.com/assets/433990/13375547/fe1d2a20-dda2-11e5-91c7-1155db7c49da.png">

Installing with Bower gives me what I’m looking for:

<img width="206" alt="screen shot 2016-02-27 at 22 40 43" src="https://cloud.githubusercontent.com/assets/433990/13375558/3144b742-dda3-11e5-8e17-b724f9f88cc5.png">

Is there an issue with the NPM installation?

:wave:

**Comment by jxnblk** [comment] 2016-03-01 18:03
I'm not able to reproduce this. The `prepublish` script here should transpile the source to scss on install. https://github.com/basscss/basscss-sass/blob/master/package.json#L8

What version of npm are you using?

**Comment by shanecarmody** [comment] 2016-03-02 19:08
I installed it using `3.3.12`. I just updated to `3.7.5` but I’m getting the same result.

**Comment by jxnblk** [comment] 2016-03-03 16:37
Have you tried manually running `npm run prepublish` in the installed folder?

**Comment by shanecarmody** [comment] 2016-03-26 17:40
In which folder do you mean? Do I need to `cd` into a certain folder and run this command?

Thanks

**Comment by jxnblk** [comment] 2016-04-13 12:12
I was suggesting:

```
npm i -D basscss-sass
cd node_modules/basscss-sass
npm run prepublish
```

**Comment by jxnblk** [comment] 2016-04-28 13:16
Closing this for now. Let me know if you're still having issues though.

**Closed as completed by jxnblk** 2016-04-28 13:16 UTC

**Comment by shanecarmody** [comment] 2016-07-12 20:34
Hi @jxnblk 

I finally got around to testing this. The `npm i -D basscss-sass` command seemed to install things the way I wanted to but there was a problem when I ran the `npm run prepublish` command. I got the following output in Terminal:

```
$ npm run prepublish

> basscss-sass@4.0.0 prepublish /Users/me/Sites/sample-site/node_modules/basscss-sass
> node build

module.js:327
    throw err;
    ^

Error: Cannot find module 'css-scss'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/me/Sites/sample-site/node_modules/basscss-sass/build.js:5:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "prepublish"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE
npm ERR! basscss-sass@4.0.0 prepublish: `node build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the basscss-sass@4.0.0 prepublish script 'node build'.
npm ERR! This is most likely a problem with the basscss-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs basscss-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls basscss-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/me/Sites/sample-site/node_modules/basscss-sass/npm-debug.log
```

Thanks for your help.

**Comment by shanecarmody** [comment] 2016-07-12 20:35
Here’s what the Node package installation looked like:

<img width="216" alt="screen shot 2016-07-12 at 22 35 09" src="https://cloud.githubusercontent.com/assets/433990/16782686/f8bc009e-4880-11e6-8ab3-5d24f07306ac.png">
