### ISSUE TITLE
Invalid CSS after "...value:  bold */"

### ISSUE THREAD

**Issue by julienfroidefond** [basscss/basscss-sass#8] opened 2015-12-01 11:37 UTC
Hi,

I get this error with a bower integration + gulp sass compilation :

```
Error: web/bundles/app/sass/basscss-sass/_btn.scss
Error: Invalid CSS after "...value:  bold */": expected 1 selector or at-rule, was "!default;"
        on line 61 of web/bundles/app/sass/basscss-sass/_btn.scss
>> ld-font-weight /* Fallback value:  bold */ !default;
```

If I remove the comment all gets working. Can you repare this from the repo plz ? I'd prefer to use Bower instead of my proper copy and correction.

Thx

**Comment by johno** [comment] 2015-12-01 14:57
Duplicate of #6, will be solved with a new `$ npm publish`

cc/ @jxnblk

**Comment by julienfroidefond** [comment] 2015-12-01 14:58
Sorry

**Comment by johno** [comment] 2015-12-01 15:17
Not a problem. My apologies for coming off a little abrupt there. Thanks for taking the time to report : ) :beers:

**Closed as completed** 2016-02-14 00:37 UTC
